version: "3.9"

services:
  web:
    container_name: pomodoro-todo-nginx-container
    build:
      context: .
      dockerfile: Dockerfile
    image: krcdocker2138/pomodoro-todo-webapp
    ports:
      - "80:80"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 5s
      retries: 3

